### ISSUE TITLE
bug: Named export 'CancelablePromise' not found

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-files#1058]
I get this error

```
SyntaxError: Named export 'CancelablePromise' not found. The requested module 'cancelable-promise' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'cancelable-promise';
const { CancelablePromise } = pkg;
```
when trying to run `npm run test` with `@nextcloud/files@3.8.0`, see here https://github.com/raimund-schluessler/inventory/pull/610. It seems there is a problem with the import here
https://github.com/nextcloud-libraries/nextcloud-files/blob/bc9750441cc7c7611df441640cb7c66475ffc13b/lib/dav/dav.ts#L17

Is this an error with the package, or do I use it wrong? It used to work fine with 3.1.1.

**Comment by skjnldsv** [comment]
cc @susnux

**Comment by susnux** [comment]
The import is correct, it is not a CJS module but provides both.
Also our ESM entry correctly imports it and the CJS entry also correctly requires the CJS entry.

So the problem here is that the `cancelable-promise` package does not correctly provide their exports,
they provide "main" and "module" but this is ignored and the package does not provide "export".
Vitest will pass all dependencies (`node_modules`) directly to Node without the Vite pipeline, but this will not work here (you can see that build works because of Vite but tests do not).

Fixes possible:
1. Upstream add the missing `exports`
2. You inline the dependency so it gets transpiled by Vite

In general all `@nextcloud` libraries do not target Node but the Browser, so I think it would be the safest to change your config to:

```diff
     server: {
       deps: {
-        inline: ['@nextcloud/vue'],
-      }
+        inline: [/@nextcloud\//],
+      },
     },
```

**Comment by raimund-schluessler** [comment]
@susnux Thanks a lot for looking into this! Inlining the dependencies works. Is it a general recommendation to inline all nextcloud dependencies? We might stumble upon this more often, when we migrate more apps to `vite/st` I suppose.

Closing this issue, since there is a fix.

**Comment by susnux** [comment]
Well we have the same problem with other test runners like jest too.
The problem is they are meant for Node, so they think packages are for Node.js, but we do not target Node.js but Browsers, so our packages are built with Browsers in mind.

Meaning most of the test runners try to boost the performance by just letting Node execute the dependencies instead of transpiling. It is not really related to `vite` in this case.

But to answer your question: Yes I would recommend to always transpile `@nextcloud/` libraries for the reasons mentioned :)
